#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2010 Eric Allen
#
# Author: Eric Allen <eric@hackerengineer.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import dripbox
import re
import logging
import argparse
import sys
import os
import getpass

LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
REMOTE_MATCH = re.compile("(.+@)?(.+):(.+)").match

logging.basicConfig(level=logging.INFO)
# parse arguments
parser = argparse.ArgumentParser(
        description='Automatically sync local files to remote')
parser.add_argument('-p', '--remote-port',
        type=int, help="SSH port on remote system")
parser.add_argument('remote', nargs=1, metavar="USER@HOST:PATH")
args = parser.parse_args()


def parse_remote(remote):
    username, host, remote_root = REMOTE_MATCH(remote).groups()
    if username:
        username = username.rstrip('@')
    else:
        username = getpass.getuser()

    return dict(username=username, host=host, remote_path=remote_root)

launch_args = parse_remote(args.remote[0])
launch_args['port'] = args.remote_port
dripbox.launch(**launch_args)

print("Hit ENTER to quit")
raw_input()
sys.exit(0)
